### ISSUE TITLE
not great to render for instance the ARRAY source code

### ISSUE THREAD

**Issue by jocelyn** [Conaclos/prism#2]
I tried http://prismjs.com/test.html using the source code from ARRAY "https://svn.eiffel.com/eiffelstudio/trunk/Src/library/base/elks/kernel/array.e"

and the rendering has a few trouble, I guess related to string like  "[]"

**Comment by Conaclos** [comment]
Hi,

Good catch!
https://github.com/LeaVerou/prism/pull/476 fixes this issue.

**Comment by jocelyn** [comment]
Thanks.
